name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv run mkdocs build
      - uses: actions/upload-artifact@v4
        with:
          name: mkdocs-site
          path: site/
