name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/action-build.yaml
  push-oras:
    uses: ./.github/workflows/action-push-oras.yaml
    needs: build
