name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  autocorrect:
    uses: ./.github/workflows/action-autocorrect.yml
  build:
    uses: ./.github/workflows/action-build.yml
  push-oras:
    uses: ./.github/workflows/action-push-oras.yml
    needs: build
